#Wai Shing Yung

all : checksum.out polygon.out election.out

checksum.out : checksum.c
	gcc -Wall -g -o checksum.out checksum.c

polygon.out : polygon.c
	gcc -Wall -g -o polygon.out polygon.c

election.out : election.c
	gcc -Wall -g -o election.out election.c
