#Wai Shing Yung 996936848

all : reverse.out suffix.out names.out

reverse.out: reverse.c
	gcc -Wall -g -o reverse.out reverse.c

suffix.out: suffix.c
	gcc -Wall -g -o suffix.out suffix.c

names.out: names.c
	gcc -Wall -g -o names.out names.c


