#Authors: Christopher Chen (997549548), Wai Shing Yung (996936848)
#"Live by the code, die by the code."

all: p8.out p8b.out

p8.out: main.cpp SVector.h
	g++ -DNDEBUG -Wall -g -ansi -o p8.out main.cpp
	
p8b.out: main.cpp SVector.h
	g++ -Wall -g -ansi -o p8b.out main.cpp
	
clean:
	rm -f p8.out p8b.out
