all: names.out reverse.out suffix.out

names.out: names.c 
	g++ -Wall -ansi  -o names.out names.c

reverse.out: reverse.c 
	g++ -Wall -ansi  -o reverse.out reverse.c

suffix.out: suffix.c 
	g++ -Wall -ansi  -o suffix.out suffix.c

clean:
	rm -f names.out reverse.out suffix.out 
